name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      DATE: $(date +%s)

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_REGISTRY }}ms-ditribution:${{ env.DATE }}
    - name: Login to Dockerhub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to docker
      run: docker image push ${{ secrets.DOCKER_REGISTRY }}ms-ditribution:${{ env.DATE }}
